Ability to select media type
BruelAndKjaer/Chafu pull request #17
Opened 2016-10-17 13:54 UTC by Prin53

In this PR you can specify media type you need when creating `ChafuViewController`:

```
new ChafuViewController
{
	LazyDataSource = (albumView, size, mediaTypes) => new PhotoGalleryDataSource(albumView, size, MediaType.Photo | MediaType.Video)
};
```

The default data source will have the same behavior: to show both photo and video.

2016-10-17 21:43 UTC, Cheesebaron requested changes
Thank you for this pull request. Please fix the requested changes commented per file.

In general, convert tabs to 4 spaces.

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/PhotoGalleryDataSource.cs
> +		public PhotoGalleryDataSource(AlbumView albumView, CGSize cellSize, MediaType mediaTypes)
Please add default value to the ctor and add to the comment above.

Convert tab to 4 spaces

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/PhotoGalleryDataSource.cs
> +			_mediaTypes = mediaTypes;
Convert tab to 4 spaces

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/PhotoGalleryDataSource.cs
> +				var assets = new List<PHAsset>();
Convert tab to 4 spaces

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/PhotoGalleryDataSource.cs
> +			if (assets == null)
Convert tab to 4 spaces

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/PhotoGalleryDataSource.cs
> +			{
Remove { } around statement

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/PhotoGalleryDataSource.cs
> +				if (_images != null)
Split out in own method.

Convert tab to 4 spaces.

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/MediaType.cs
> +	public enum MediaType
Convert tab to 4 spaces

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/MediaType.cs
> +	public enum MediaType
There is already a MediaType class here: https://github.com/BruelAndKjaer/Chafu/blob/a51cbbcf0a5c70c0e2d08f7e020129e15fdb3aed/Chafu/BaseAlbumDataSource.cs#L9 use that

2016-10-17 21:43 UTC, Cheesebaron commented on Chafu/AlbumViewController.cs
> +			AlbumDataSource = LazyDataSource(_album, CellSize, MediaType.Photo | MediaType.Video);
Convert tabs to 4 spaces each

2016-10-18 08:38 UTC, Prin53 commented
@Cheesebaron thank you for your comments. I pushed related changes.

2016-10-18 08:58 UTC, Cheesebaron approved these changes
Looks good 👍

2016-10-18 09:03 UTC, Cheesebaron commented
Will give it a spin when I have access to an iPhone again.

2016-10-31 23:13 UTC, merged

2016-11-01 00:27 UTC, Cheesebaron commented
This is out in the 1.5.0 NuGet. Thanks 👍